### ISSUE TITLE
Exception lors de l'édition du relevé de notes d'un étudiant

### ISSUE THREAD

**Issue by gmartel** [EsupPortail/esup-ects#2]
Bonjour,

L'édition du relevé de notes provoque l'exception suivante sur certains environnements.
`ERROR [org.esupportail.ects.web.controllers.PrintController] - net.sf.jasperreports.engine.util.JRFontNotFoundException: Font 'Arial' is not available to the JVM. See the Javadoc for more details.`

A noter, l'édition de la distribution des notes dans le même environnement ne provoque pas d'exception.

**Comment by nhenry** [comment]
Résolu en version 1.3.1.
La police DejaVu Sans est maintenant utilisée car présente dans la JVM. Le template jrxml a été adapté en conséquences.
L'utilisation d'une autre police imposerait une dépendance supplémentaire à maintenir.
